/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TheAbout copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAbout: typeof import('./src/components/TheAbout.vue')['default']
    TheAttendance: typeof import('./src/components/TheAttendance.vue')['default']
    TheBanner: typeof import('./src/components/TheBanner.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheGallery: typeof import('./src/components/TheGallery.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
